apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: repo_entity
  description: The place to be, for great artists
spec:
  type: website
  lifecycle: production
  owner: artist-relations-team
  system: artist-engagement-portal
  providesApis:
    - artist-api
